### ISSUE TITLE
Use async-await on metrics

### ISSUE THREAD

**Issue by Luni-4** [rust-av/av-metrics#35]
Since the `async-await` construct is now stable on Rust, it would be helpful to use it on metrics in order to speed up their computation.

**Comment by Luni-4** [comment]
@shssoichiro 

Is this still relevant for `av-metrics`?

**Comment by shssoichiro** [comment]
I'm not sure that there's a need for this. async normally is better for applications with many small parallel tasks, like web requests. Given that we parallelize on the frame level, our current implementation with crossbeam and rayon is probably fine and async would be overkill and probably give minimal benefits.
