### ISSUE TITLE
C library can no longer be built

### ISSUE THREAD

**Issue by dwbuiten** [rust-av/av-metrics#86]
The latest cargo-c cannot build av-metrics:

```
~/av-metrics$ cargo cbuild  --version
cargo-c 0.6.5
~/av-metrics$ cargo cinstall --prefix=/some/path
Error: CliError { error: Some(manifest path `/path/av-metrics/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace), exit_code: 101 }
~/av-metrics$
```

**Comment by Luni-4** [comment]
The following command should work:

` cargo cinstall --manifest-path=av_metrics/Cargo.toml --prefix=/some/path`

**Comment by dwbuiten** [comment]
Yeah, but that shoul not be needed (and is not user-friendly).

**Comment by Luni-4** [comment]
So can't you build `av-metrics` running the command above? Because if the problem is how the command is structured I think it would be better to open an issue on `cargo-c`

**Comment by dwbuiten** [comment]
That's fair, I'll do that.
